variant = "loose"

[[issues]]
file = "src/AdapterPlatform.php"
code = "literal-named-argument"
message = """Literal argument `'""'` should be passed as a named argument for clarity."""
count = 1

[[issues]]
file = "src/ConfigProvider.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 2

[[issues]]
file = "src/Connection.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Connection.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Connection.php"
code = "literal-named-argument"
message = "Literal argument `' '` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Connection.php"
code = "literal-named-argument"
message = "Literal argument `''` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Connection.php"
code = "literal-named-argument"
message = "Literal argument `'BEGIN'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Connection.php"
code = "literal-named-argument"
message = "Literal argument `'COMMIT'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Connection.php"
code = "literal-named-argument"
message = "Literal argument `'ROLLBACK'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Connection.php"
code = "literal-named-argument"
message = """Literal argument `'SELECT CURRENT_SCHEMA AS "currentschema"'` should be passed as a named argument for clarity."""
count = 1

[[issues]]
file = "src/Connection.php"
code = "literal-named-argument"
message = '''Literal argument `'\\\''` should be passed as a named argument for clarity.'''
count = 1

[[issues]]
file = "src/Connection.php"
code = "literal-named-argument"
message = "Literal argument `'currentschema'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Connection.php"
code = "literal-named-argument"
message = "Literal argument `'currval'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Connection.php"
code = "literal-named-argument"
message = "Literal argument `0` should be passed as a named argument for clarity."
count = 2

[[issues]]
file = "src/Connection.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Connection.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Connection.php"
code = "string-style"
message = "String concatenation can be replaced with interpolation."
count = 1

[[issues]]
file = "src/Connection.php"
code = "tagged-todo"
message = "TODO should be tagged with (@username) or (#issue)."
count = 1

[[issues]]
file = "src/Connection.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/Container/PdoConnectionInterfaceFactory.php"
code = "tagged-todo"
message = "TODO should be tagged with (@username) or (#issue)."
count = 1

[[issues]]
file = "src/Container/PdoDriverInterfaceFactory.php"
code = "tagged-todo"
message = "TODO should be tagged with (@username) or (#issue)."
count = 1

[[issues]]
file = "src/Container/PlatformInterfaceFactory.php"
code = "tagged-todo"
message = "TODO should be tagged with (@username) or (#issue)."
count = 1

[[issues]]
file = "src/Driver.php"
code = "tagged-todo"
message = "TODO should be tagged with (@username) or (#issue)."
count = 1

[[issues]]
file = "src/Metadata/Source.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Metadata/Source.php"
code = "halstead"
message = "Method has a high halstead volume and effort"
count = 1

[[issues]]
file = "src/Metadata/Source.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Metadata/Source.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 4

[[issues]]
file = "src/Metadata/Source.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 5

[[issues]]
file = "src/Metadata/Source.php"
code = "string-style"
message = "String concatenation can be replaced with interpolation."
count = 4

[[issues]]
file = "src/Pdo/Connection.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Pdo/Connection.php"
code = "halstead"
message = "Method has a high halstead effort"
count = 1

[[issues]]
file = "src/Pdo/Connection.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1

[[issues]]
file = "src/Pdo/Connection.php"
code = "no-empty-catch-clause"
message = "Do not use empty `catch` blocks."
count = 1

[[issues]]
file = "src/Pdo/Connection.php"
code = "no-fully-qualified-global-class-like"
message = "Fully-qualified class-like reference detected."
count = 1

[[issues]]
file = "src/Pdo/Connection.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 7

[[issues]]
file = "src/Pdo/Connection.php"
code = "no-multi-assignments"
message = "Avoid multiple assignments in a single statement."
count = 4

[[issues]]
file = "src/Pdo/Connection.php"
code = "tagged-todo"
message = "TODO should be tagged with (@username) or (#issue)."
count = 2

[[issues]]
file = "src/Result.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/Statement.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/Statement.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Statement.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "test/asset/SetupTrait.php"
code = "no-dead-store"
message = "Variable `$serviceManagerConfig` is overwritten before its value is read."
count = 1

[[issues]]
file = "test/asset/SetupTrait.php"
code = "no-literal-namespace-string"
message = "Use `::class` notation instead of a hardcoded namespace string."
count = 2

[[issues]]
file = "test/integration/AdapterPlatformTest.php"
code = "tagged-todo"
message = "TODO should be tagged with (@username) or (#issue)."
count = 1

[[issues]]
file = "test/integration/AdapterTest.php"
code = "tagged-todo"
message = "TODO should be tagged with (@username) or (#issue)."
count = 1

[[issues]]
file = "test/integration/Extension/IntegrationTestStartedListener.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "test/integration/Extension/IntegrationTestStoppedListener.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "test/integration/FixtureLoader/PgsqlFixtureLoader.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 2

[[issues]]
file = "test/integration/FixtureLoader/PgsqlFixtureLoader.php"
code = "no-boolean-flag-parameter"
message = "Avoid boolean flag parameters."
count = 1

[[issues]]
file = "test/integration/Pdo/AdapterTest.php"
code = "no-dead-store"
message = "Variable `$isConnected` is overwritten before its value is read."
count = 1

[[issues]]
file = "test/integration/Pdo/AdapterTest.php"
code = "no-redundant-variable"
message = "Variable `$isConnected` is assigned but never used."
count = 1

[[issues]]
file = "test/integration/Pdo/AdapterTest.php"
code = "tagged-todo"
message = "TODO should be tagged with (@username) or (#issue)."
count = 1
